# This is a basic workflow to Build and Test using Actions

name: CI using Github Actions

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout pytsk
        uses: actions/checkout@v2
        with:
          repository: 'py4n6/pytsk'
          path: 'pytsk'
          
      - name: Install build dependencies for pytsk
        run: sudo apt-get install automake autotools-dev build-essential git libtool python3 python3-dev python3-distutils python3-setuptools
          
      - name: Update pytsk
        run: |
            cd pytsk
            python setup.py update
          
      - name: Build pytsk
        run: |
          cd pytsk
          python setup.py build
          
      - name: Install pytsk
        run: |
          cd pytsk
          sudo python setup.py install
          pip3 list | grep pytsk
                              
      - name: Checkout libewf
        uses: actions/checkout@v2
        with:
          repository: 'libyal/libewf'
          path: 'libewf'
          
      - name: Install dependencies for libewf
        run: sudo apt-get install build-essential debhelper fakeroot autotools-dev flex bison zlib1g-dev libbz2-dev libssl-dev libfuse-dev python-dev python-setuptools python3-dev python3-setuptools
      
      - name: Sync libs for libewf
        run: |
          cd libewf
          ./synclibs.sh
          ./autogen.sh
          ./configure --enable-python
          
      - name: Build libewf
        run: |
          cd libewf
          python setup.py build
          
      - name: Install libewf
        run: |
          cd libewf
          sudo python setup.py install
          pip3 list
          
      - name: Checkout slack_handler
        uses: actions/checkout@v2
        with:
          path: 'slack_handler'
          
      - name: Test slack_handler
        run: |
          pip3 install pytest
          cd slack_handler
          pytest test_slack_handler.py
