# This is a basic workflow to test with Actions

name: CI using Github Actions

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
      - name: setup pytsk
        uses: actions/checkout@v2
        with:
          repository: 'py4n6/pytsk'
          path: 'pytsk'
          
      - name: update pytsk
        run: |
            cd pytsk
            python setup.py update
          
      - name: build pytsk
        run: |
          cd pytsk
          python setup.py build
          
      - name: install pytsk
        run: |
          cd pytsk
          sudo python setup.py install
          pip list | grep pytsk
                              
      - name: setup libewf
        uses: actions/checkout@v2
        with:
          repository: 'libyal/libewf'
          path: 'libewf'

      # Runs a single command using the runners shell
      - name: Sync libs
        run: |
          cd libewf
          ./synclibs.sh
          ./autogen.sh
          ./configure --enable-python
          
      - name: build pyewf
        run: |
          cd libewf
          python setup.py build
          
      - name: install pyewf
        run: |
          cd libewf
          sudo python setup.py install
          pip list | grep pyewf
          
      - name: setup slack_handler
        uses: actions/checkout@v2
        with:
          path: 'slack_handler'
        
      - name: Run a multi-line script
        run: |
          sudo apt-get install tree
          tree -L 2
          
      - name: test
        run: |
          pip install pytest
          cd slack_handler
          pytest test_slack_handler.py
