# This is a basic workflow to Build and Test using Actions

name: Build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout slack_handler
        uses: actions/checkout@v2
        with:
          path: 'slack_handler'
          
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install pipenv
        run: |
          python3 -m pip install --upgrade pipenv wheel
          
      - name: Cache it out
        id: cache-pipenv
        uses: actions/cache@v2
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('slack_handler/Pipfile.lock') }}
          restore-keys: |
              ${{ runner.os }}-pipenv-
      
      - name: Run pipenv
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          cd slack_handler
          pipenv install --dev --deploy
      
      - name: Checkout pytsk
        uses: actions/checkout@v2
        with:
          repository: 'py4n6/pytsk'
          path: 'pytsk'
          
      - name: Install build dependencies for pytsk
        run: sudo apt-get install automake autotools-dev build-essential git libtool python3 python3-dev python3-distutils python3-setuptools
          
      - name: Update pytsk
        run: |
            cd pytsk
            python3 setup.py update
          
      - name: Build pytsk
        run: |
          cd pytsk
          python3 setup.py build --verbose
          
      - name: Install pytsk
        run: |
          cd pytsk
          pipenv run pip install -e .
                              
      - name: Checkout libewf
        uses: actions/checkout@v2
        with:
          repository: 'libyal/libewf'
          path: 'libewf'
          
      - name: Install dependencies for libewf
        run: sudo apt-get install build-essential debhelper fakeroot autotools-dev flex bison zlib1g-dev libbz2-dev libssl-dev libfuse-dev python-dev python-setuptools python3-dev python3-setuptools
      
      - name: Sync libs and build libewf
        run: |
          cd libewf
          ./synclibs.sh
          ./autogen.sh
          ./configure --enable-python3
          python3 setup.py build --verbose
          
      - name: Install libewf
        run: |
          cd libewf
          pipenv run pip install -e .
          
      - name: Check needed modules
        run: |
          cd slack_handler/
          pipenv run pip list
          pip3 list
          pipenv run pip list | grep pytsk
          pipenv run pip list | grep libewf
          pipenv run pip list | grep pytest
        
      - name: Test slack_handler
        run: |
          cd slack_handler/
          pipenv run pytest tests/test_slack_handler.py
